### ISSUE TITLE
Fails to checkout branches from forks

### ISSUE THREAD

**Issue by mvilanova** [samuelmeuli/lint-action#27] opened 2020-03-12 23:14 UTC
```
Run samuelmeuli/lint-action@v1.2.0
Fetching all remote Git branches
From https://github.com/Netflix/dispatch
Checking out the "remove_unused_args" branch
 * [new branch]      bugfix/stable-time -> origin/bugfix/stable-time
 * [new branch]      develop            -> origin/develop
 * [new branch]      docs               -> origin/docs
 * [new branch]      feature/dashboard  -> origin/feature/dashboard
 * [new branch]      feature/update-incident-document -> origin/feature/update-incident-document
 * [new branch]      master             -> origin/master
error: pathspec 'remove_unused_args' did not match any file(s) known to git
Error: Command failed: git checkout remove_unused_args
error: pathspec 'remove_unused_args' did not match any file(s) known to git

    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at run (/home/runner/work/_actions/samuelmeuli/lint-action/v1.2.0/src/utils/action.js:69:18)
    at Object.checkOutBranch (/home/runner/work/_actions/samuelmeuli/lint-action/v1.2.0/src/git.js:9:2)
    at runAction (/home/runner/work/_actions/samuelmeuli/lint-action/v1.2.0/src/index.js:35:7)
    at Object.<anonymous> (/home/runner/work/_actions/samuelmeuli/lint-action/v1.2.0/src/index.js:93:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14) {
  status: 1,
  signal: null,
  output: [
    null,
    '',
    "error: pathspec 'remove_unused_args' did not match any file(s) known to git\n"
  ],
  pid: 3775,
  stdout: '',
  stderr: "error: pathspec 'remove_unused_args' did not match any file(s) known to git\n"
}
/home/runner/work/_actions/samuelmeuli/lint-action/v1.2.0/src/index.js:15
	throw new Error(`Exiting because of unhandled promise rejection`);
	^
```
Workflow file here: https://github.com/Netflix/dispatch/blob/develop/.github/workflows/list_and_test.yml

**Comment by samuelmeuli** [comment] 2020-03-14 02:50
Probably a duplicate of #13.

There will be more helpful error messages in the next release (added in d9658261db602ac926c21fe4e3d446407990c1b1).

**Closed by samuelmeuli** 2020-03-14 02:50 UTC
