### ISSUE TITLE
Allow passing files to check into linters

### ISSUE THREAD

**Issue by dorner** [samuelmeuli/lint-action#20] opened 2020-02-20 18:22 UTC
We've got a large legacy repo and I'd like to implement a Github Action to only lint *changed* files. Running a linter on the entire repo is not currently a possibility.

I'm using https://github.com/trilom/file-changes-action to detect these files, but it looks like the lint action has no way of passing them into the linters.

E.g. for Rubocop, it automatically adds a "." to the command which forces all files under the directory to be linted.

It'd be great if we could make this a general feature. Failing that I can look at fixing rubocop so it allows for passed-in files (the "." should be redundant).

**Comment by samuelmeuli** [comment] 2020-02-22 08:27
Hi @dorner, thanks for opening the issue!

Please see https://github.com/samuelmeuli/lint-action/issues/1 about why detection of changed files isn't built into the action.

Specifying the files/directories to lint is a valid request. The problem is that linters implement this in different ways (list of files, regex, both) or don't support it at all (only allow linting the entire project). Furthermore, a new option would probably conflict with the `[linter]_extensions` setting.

I'm open for suggestions as to how this could be implemented in a cleaner yet consistent way :)

**Comment by dorner** [comment] 2020-02-24 14:54
Fair enough. I don't have a ton of experience with linters outside Rubocop to be honest (I've used eslint but not extensively). I think as long as we ensure that linters can accept this argument as part of their `[linter]_args` input that should be sufficient.

**Comment by dorner** [comment] 2020-02-24 14:56
Btw I think that even though the annotations might not be accurate for detecting changed files, the case where annotations are an afterthought and the thing that really counts is the auto-fix and pass/fail check gives enough value for us to use this feature. For now I'm tying this together with the aforementioned file-changes-action to accomplish this. I'm not sure it's necessarily in the purview of this action to enable this feature though - I think it's fine to meld the two together and pass in the list of files if people need it.

**Comment by tmc** [comment] 2020-02-24 19:09
Is it an option to allow custom shell code to run for a particular linter? 

flake8 has a --diff flag such that running `git diff master... | flake8 --diff` produces output for just the files that have been modified from master which would be helpful to be able to do.

**Comment by dorner** [comment] 2020-02-24 20:35
Yeah that's what I was thinking with a generalized `command_prefix` option. The parent code could just prepend that prefix to the actual command.

**Comment by samuelmeuli** [comment] 2020-03-28 23:50
Closing this issue as `[linter]_command_prefix` can now be used to achieve this.

**Closed by samuelmeuli** 2020-03-28 23:50 UTC
Labels: enhancement
